#ifndef _OEM_SMEM_H_
#define _OEM_SMEM_H_

  SMEM_SMEM_LOG_PM,
  SMEM_ABNORMAL_RESET_LOG,
  SMEM_OTP_DATA_NV_DATA_CURRENTLY,
  SMEM_OTP_DATA_FROM_DT_OR_DIAG,
  SMEM_QISDA_DIAGPKT_REQ_RSP,
  SMEM_SMEM_BATT_PM_LOG,
  SMEM_HW_ID,
#endif
