obj-$(CONFIG_ANDROID_BINDER_IPC)	+= binder.o
obj-$(CONFIG_ANDROID_LOGGER)		+= logger.o
obj-$(CONFIG_ANDROID_RAM_CONSOLE)	+= ram_console.o
obj-$(CONFIG_ANDROID_TIMED_OUTPUT)	+= timed_output.o
obj-$(CONFIG_ANDROID_TIMED_GPIO)	+= timed_gpio.o
obj-$(CONFIG_ANDROID_LOW_MEMORY_KILLER)	+= lowmemorykiller.o

# Jagan+
obj-$(CONFIG_ANDROID_MODEM_TRACE_DRIVER) += modem_logger.o
obj-$(CONFIG_ANDROID_KERNEL_EVENT_DRIVER) += kernel_event.o
obj-$(CONFIG_LOG_FILTER) += logger_filter.o
# Jagan-

